// <auto-generated />
using System;
using BestFood.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BestFood.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BestFood.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "bcc9e639-b998-466b-8d67-5e7dda1dfe5a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "60e38fc0-ea77-4385-a95e-2cb21fceb770",
                            Email = "myadmin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MYADMIN@GMAIL.COM",
                            NormalizedUserName = "MYADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEPdGKRarAFI9aEPFvqW9OUcGqERe6Nyl5O1BN59eRnLLpBRgKTB3tmwYTC0BFYL7pg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3ab2869f-5246-407b-9a2e-9779a73531f4",
                            TwoFactorEnabled = false,
                            UserName = "myadmin@gmail.com"
                        });
                });

            modelBuilder.Entity("BestFood.Infrastructure.Data.Models.CartItem", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("BestFood.Infrastructure.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://insanelygoodrecipes.com/wp-content/uploads/2020/05/Burger-with-fries-1024x536.png",
                            Name = "Burgers"
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://static.toiimg.com/photo/msid-87930581/87930581.jpg?211826",
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://t4.ftcdn.net/jpg/02/58/85/85/360_F_258858591_9cHoK7D35fpe4IO1JPyjXyuDV0HUMPSM.jpg",
                            Name = "Doner"
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/delish-191112-risotto-rice-0151-landscape-pf-1574723947.jpg",
                            Name = "Rissoto"
                        },
                        new
                        {
                            Id = 5,
                            Image = "https://roseandsteinrestaurant.eu/wp-content/uploads/2016/12/ham-and-cheese-toast.jpg",
                            Name = "Toasts"
                        });
                });

            modelBuilder.Entity("BestFood.Infrastructure.Data.Models.CategoryIngredient", b =>
                {
                    b.Property<string>("IngredientId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("IngredientId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryIngredients");

                    b.HasData(
                        new
                        {
                            IngredientId = "0ad836b1-0b01-4b4a-ba36-9ded54ebaa85",
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = "d9979ac9-3401-4257-aded-cc37edd3becb",
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = "256a3217-f445-436e-b763-26829df121c6",
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = "f6903024-2ae3-403e-b7f4-a5cf074e4af7",
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = "0f1fa492-6a74-4b89-bde7-0f8d73d66277",
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = "33458ae4-b21f-4c39-8dff-44e87844a6a2",
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = "e4726844-83be-4631-8adb-b4e0ed0e4145",
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = "f6dec5d8-15c5-4074-afa9-0b218f18a5f3",
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = "6d1898d5-e4e5-4c4e-aed5-a9208b1ccf2b",
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = "53d5a668-8b04-45d3-be64-60e8ae439894",
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = "84def27a-0f81-4532-9907-1645aa7ee027",
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = "55fc746a-0a85-4923-a3ce-7a8beb914370",
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = "e7791135-4cd6-4c94-afe9-1867dc19c338",
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = "4e3b02ca-c436-4827-bc1d-6a283ba44a54",
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = "68f92dc1-85aa-4876-b86a-8ed4313deaae",
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = "20f84ff4-662d-4f0a-bc66-e9170c215a2a",
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = "2a63b060-acc5-41ad-844d-31209d33fa10",
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = "0b11bbb6-0d3d-4233-8f94-c6e11f9682fb",
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = "813bde29-b392-4c16-9a3f-65734d667b08",
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = "b48f7dc6-4077-4bfb-8ed4-8f4e8d616908",
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = "58fbb498-4393-41d2-a0e7-d0c364a36cc5",
                            CategoryId = 1
                        },
                        new
                        {
                            IngredientId = "d9979ac9-3401-4257-aded-cc37edd3becb",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "256a3217-f445-436e-b763-26829df121c6",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "f6903024-2ae3-403e-b7f4-a5cf074e4af7",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "0f1fa492-6a74-4b89-bde7-0f8d73d66277",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "33458ae4-b21f-4c39-8dff-44e87844a6a2",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "e4726844-83be-4631-8adb-b4e0ed0e4145",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "2f723a91-bc11-4104-bb01-6d4ebbc60fc5",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "b372fe32-ee80-4d63-9019-9e9d9c87cd99",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "bb1979e9-4c7b-412c-9e84-4598bfa0524e",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "8b596d55-2f13-45c0-80e3-b023434a14df",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "8eb5383e-2440-4075-8aab-a774351a6153",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "c20d21eb-326f-4011-b8ba-058399d972c6",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "e7791135-4cd6-4c94-afe9-1867dc19c338",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "20f84ff4-662d-4f0a-bc66-e9170c215a2a",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "2a63b060-acc5-41ad-844d-31209d33fa10",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "a3b2844c-a654-40cd-8045-e93d89826173",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "b8ae6779-3469-4669-89f2-932b49d46fdc",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "0b11bbb6-0d3d-4233-8f94-c6e11f9682fb",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "b48f7dc6-4077-4bfb-8ed4-8f4e8d616908",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "813bde29-b392-4c16-9a3f-65734d667b08",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "e9bf191c-3475-4240-885c-19daba91ca80",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "5bb1a785-d1f7-4c2d-9da5-cf456df1bfaa",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "e9fbd357-86b4-4f6d-9368-c6434b7a318f",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "392ff29a-68b8-4c7c-81d6-a5deb6d5a0c2",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "4762b0c6-1d7f-468a-b4a9-a71d8b1c20f2",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "5e27ab2b-8ed1-4f3b-87bd-cc52394088b4",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "71a2378d-74de-4c9a-a64b-237820a5b6b9",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "9ad3222f-77f7-4d4e-b9a3-66030e993e67",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "58fbb498-4393-41d2-a0e7-d0c364a36cc5",
                            CategoryId = 2
                        },
                        new
                        {
                            IngredientId = "d9979ac9-3401-4257-aded-cc37edd3becb",
                            CategoryId = 3
                        },
                        new
                        {
                            IngredientId = "256a3217-f445-436e-b763-26829df121c6",
                            CategoryId = 3
                        },
                        new
                        {
                            IngredientId = "f6903024-2ae3-403e-b7f4-a5cf074e4af7",
                            CategoryId = 3
                        },
                        new
                        {
                            IngredientId = "0f1fa492-6a74-4b89-bde7-0f8d73d66277",
                            CategoryId = 3
                        },
                        new
                        {
                            IngredientId = "33458ae4-b21f-4c39-8dff-44e87844a6a2",
                            CategoryId = 3
                        },
                        new
                        {
                            IngredientId = "e4726844-83be-4631-8adb-b4e0ed0e4145",
                            CategoryId = 3
                        },
                        new
                        {
                            IngredientId = "c751debf-36b1-4801-af56-8c9096f34309",
                            CategoryId = 3
                        },
                        new
                        {
                            IngredientId = "e7791135-4cd6-4c94-afe9-1867dc19c338",
                            CategoryId = 3
                        },
                        new
                        {
                            IngredientId = "20f84ff4-662d-4f0a-bc66-e9170c215a2a",
                            CategoryId = 3
                        },
                        new
                        {
                            IngredientId = "2a63b060-acc5-41ad-844d-31209d33fa10",
                            CategoryId = 3
                        },
                        new
                        {
                            IngredientId = "0b11bbb6-0d3d-4233-8f94-c6e11f9682fb",
                            CategoryId = 3
                        },
                        new
                        {
                            IngredientId = "b48f7dc6-4077-4bfb-8ed4-8f4e8d616908",
                            CategoryId = 3
                        },
                        new
                        {
                            IngredientId = "33458ae4-b21f-4c39-8dff-44e87844a6a2",
                            CategoryId = 4
                        },
                        new
                        {
                            IngredientId = "e7791135-4cd6-4c94-afe9-1867dc19c338",
                            CategoryId = 4
                        },
                        new
                        {
                            IngredientId = "c751debf-36b1-4801-af56-8c9096f34309",
                            CategoryId = 4
                        },
                        new
                        {
                            IngredientId = "20f84ff4-662d-4f0a-bc66-e9170c215a2a",
                            CategoryId = 4
                        },
                        new
                        {
                            IngredientId = "b8ae6779-3469-4669-89f2-932b49d46fdc",
                            CategoryId = 4
                        },
                        new
                        {
                            IngredientId = "0b11bbb6-0d3d-4233-8f94-c6e11f9682fb",
                            CategoryId = 4
                        },
                        new
                        {
                            IngredientId = "d9979ac9-3401-4257-aded-cc37edd3becb",
                            CategoryId = 5
                        },
                        new
                        {
                            IngredientId = "256a3217-f445-436e-b763-26829df121c6",
                            CategoryId = 5
                        },
                        new
                        {
                            IngredientId = "f6903024-2ae3-403e-b7f4-a5cf074e4af7",
                            CategoryId = 5
                        },
                        new
                        {
                            IngredientId = "0f1fa492-6a74-4b89-bde7-0f8d73d66277",
                            CategoryId = 5
                        },
                        new
                        {
                            IngredientId = "33458ae4-b21f-4c39-8dff-44e87844a6a2",
                            CategoryId = 5
                        },
                        new
                        {
                            IngredientId = "e4726844-83be-4631-8adb-b4e0ed0e4145",
                            CategoryId = 5
                        },
                        new
                        {
                            IngredientId = "2f723a91-bc11-4104-bb01-6d4ebbc60fc5",
                            CategoryId = 5
                        },
                        new
                        {
                            IngredientId = "bb1979e9-4c7b-412c-9e84-4598bfa0524e",
                            CategoryId = 5
                        },
                        new
                        {
                            IngredientId = "8eb5383e-2440-4075-8aab-a774351a6153",
                            CategoryId = 5
                        },
                        new
                        {
                            IngredientId = "84def27a-0f81-4532-9907-1645aa7ee027",
                            CategoryId = 5
                        },
                        new
                        {
                            IngredientId = "55fc746a-0a85-4923-a3ce-7a8beb914370",
                            CategoryId = 5
                        },
                        new
                        {
                            IngredientId = "20f84ff4-662d-4f0a-bc66-e9170c215a2a",
                            CategoryId = 5
                        },
                        new
                        {
                            IngredientId = "2a63b060-acc5-41ad-844d-31209d33fa10",
                            CategoryId = 5
                        },
                        new
                        {
                            IngredientId = "0b11bbb6-0d3d-4233-8f94-c6e11f9682fb",
                            CategoryId = 5
                        },
                        new
                        {
                            IngredientId = "b48f7dc6-4077-4bfb-8ed4-8f4e8d616908",
                            CategoryId = 5
                        },
                        new
                        {
                            IngredientId = "813bde29-b392-4c16-9a3f-65734d667b08",
                            CategoryId = 5
                        },
                        new
                        {
                            IngredientId = "58fbb498-4393-41d2-a0e7-d0c364a36cc5",
                            CategoryId = 5
                        });
                });

            modelBuilder.Entity("BestFood.Infrastructure.Data.Models.Ingredient", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = "0ad836b1-0b01-4b4a-ba36-9ded54ebaa85",
                            Name = "Tomato Sauce",
                            Type = 1
                        },
                        new
                        {
                            Id = "d9979ac9-3401-4257-aded-cc37edd3becb",
                            Name = "Ketchup",
                            Type = 1
                        },
                        new
                        {
                            Id = "256a3217-f445-436e-b763-26829df121c6",
                            Name = "Mayonnaise",
                            Type = 1
                        },
                        new
                        {
                            Id = "f6903024-2ae3-403e-b7f4-a5cf074e4af7",
                            Name = "Burger Sauce",
                            Type = 1
                        },
                        new
                        {
                            Id = "0f1fa492-6a74-4b89-bde7-0f8d73d66277",
                            Name = "Chili Sauce",
                            Type = 1
                        },
                        new
                        {
                            Id = "33458ae4-b21f-4c39-8dff-44e87844a6a2",
                            Name = "Garlic Sauce",
                            Type = 1
                        },
                        new
                        {
                            Id = "e4726844-83be-4631-8adb-b4e0ed0e4145",
                            Name = "Mustard",
                            Type = 1
                        },
                        new
                        {
                            Id = "2f723a91-bc11-4104-bb01-6d4ebbc60fc5",
                            Name = "Ham",
                            Type = 2
                        },
                        new
                        {
                            Id = "b372fe32-ee80-4d63-9019-9e9d9c87cd99",
                            Name = "Ground Beef",
                            Type = 2
                        },
                        new
                        {
                            Id = "bb1979e9-4c7b-412c-9e84-4598bfa0524e",
                            Name = "Sausage",
                            Type = 2
                        },
                        new
                        {
                            Id = "8b596d55-2f13-45c0-80e3-b023434a14df",
                            Name = "Prosciutto",
                            Type = 2
                        },
                        new
                        {
                            Id = "8eb5383e-2440-4075-8aab-a774351a6153",
                            Name = "Bacon",
                            Type = 2
                        },
                        new
                        {
                            Id = "c20d21eb-326f-4011-b8ba-058399d972c6",
                            Name = "Pepperoni",
                            Type = 2
                        },
                        new
                        {
                            Id = "f6dec5d8-15c5-4074-afa9-0b218f18a5f3",
                            Name = "Beef Meatball",
                            Type = 2
                        },
                        new
                        {
                            Id = "6d1898d5-e4e5-4c4e-aed5-a9208b1ccf2b",
                            Name = "Pork Meatball",
                            Type = 2
                        },
                        new
                        {
                            Id = "53d5a668-8b04-45d3-be64-60e8ae439894",
                            Name = "Minced Meatball",
                            Type = 2
                        },
                        new
                        {
                            Id = "84def27a-0f81-4532-9907-1645aa7ee027",
                            Name = "Pork Loin",
                            Type = 2
                        },
                        new
                        {
                            Id = "55fc746a-0a85-4923-a3ce-7a8beb914370",
                            Name = "Chicken fillet",
                            Type = 2
                        },
                        new
                        {
                            Id = "e7791135-4cd6-4c94-afe9-1867dc19c338",
                            Name = "Chicken",
                            Type = 2
                        },
                        new
                        {
                            Id = "c751debf-36b1-4801-af56-8c9096f34309",
                            Name = "Pork",
                            Type = 2
                        },
                        new
                        {
                            Id = "4e3b02ca-c436-4827-bc1d-6a283ba44a54",
                            Name = "Breaded Chicken",
                            Type = 2
                        },
                        new
                        {
                            Id = "68f92dc1-85aa-4876-b86a-8ed4313deaae",
                            Name = "Cornflake Chicken",
                            Type = 2
                        },
                        new
                        {
                            Id = "20f84ff4-662d-4f0a-bc66-e9170c215a2a",
                            Name = "Tomato",
                            Type = 3
                        },
                        new
                        {
                            Id = "2a63b060-acc5-41ad-844d-31209d33fa10",
                            Name = "Cucumber",
                            Type = 3
                        },
                        new
                        {
                            Id = "b8ae6779-3469-4669-89f2-932b49d46fdc",
                            Name = "Corn",
                            Type = 3
                        },
                        new
                        {
                            Id = "0b11bbb6-0d3d-4233-8f94-c6e11f9682fb",
                            Name = "Onion",
                            Type = 3
                        },
                        new
                        {
                            Id = "b48f7dc6-4077-4bfb-8ed4-8f4e8d616908",
                            Name = "Cabbage",
                            Type = 3
                        },
                        new
                        {
                            Id = "813bde29-b392-4c16-9a3f-65734d667b08",
                            Name = "Lettuce",
                            Type = 3
                        },
                        new
                        {
                            Id = "e9bf191c-3475-4240-885c-19daba91ca80",
                            Name = "Bell Peppers",
                            Type = 3
                        },
                        new
                        {
                            Id = "5bb1a785-d1f7-4c2d-9da5-cf456df1bfaa",
                            Name = "Spicy Red Pepper",
                            Type = 3
                        },
                        new
                        {
                            Id = "e9fbd357-86b4-4f6d-9368-c6434b7a318f",
                            Name = "Arugula",
                            Type = 3
                        },
                        new
                        {
                            Id = "392ff29a-68b8-4c7c-81d6-a5deb6d5a0c2",
                            Name = "Spinach",
                            Type = 3
                        },
                        new
                        {
                            Id = "a3b2844c-a654-40cd-8045-e93d89826173",
                            Name = "Basil",
                            Type = 3
                        },
                        new
                        {
                            Id = "4762b0c6-1d7f-468a-b4a9-a71d8b1c20f2",
                            Name = "White Cheese",
                            Type = 4
                        },
                        new
                        {
                            Id = "5e27ab2b-8ed1-4f3b-87bd-cc52394088b4",
                            Name = "Mozzarella",
                            Type = 4
                        },
                        new
                        {
                            Id = "71a2378d-74de-4c9a-a64b-237820a5b6b9",
                            Name = "Parmesan",
                            Type = 4
                        },
                        new
                        {
                            Id = "9ad3222f-77f7-4d4e-b9a3-66030e993e67",
                            Name = "Cheddar",
                            Type = 4
                        },
                        new
                        {
                            Id = "58fbb498-4393-41d2-a0e7-d0c364a36cc5",
                            Name = "Yellow Cheese",
                            Type = 4
                        },
                        new
                        {
                            Id = "b1b16da7-738b-4211-a5e2-b8f6f62cd986",
                            Name = "Butter",
                            Type = 4
                        });
                });

            modelBuilder.Entity("BestFood.Infrastructure.Data.Models.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductsInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BestFood.Infrastructure.Data.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("WeightInGrams")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "272970b2-99e5-489e-862f-0a40115b888d",
                            CategoryId = 1,
                            Image = "https://flaevor.com/wp-content/uploads/2020/09/SambalFriedChickenBurgerRecipe.jpg",
                            Name = "Breaded Chicken",
                            Price = 4.50m,
                            WeightInGrams = 300
                        },
                        new
                        {
                            Id = "ce94928c-75eb-402d-a905-9ac43aa78067",
                            CategoryId = 1,
                            Image = "https://embed.widencdn.net/img/beef/tlxkgiiioj/1120x840px/lean-mean-cheeseburgers-horizotnal.tif?keep=c&u=7fueml",
                            Name = "Beef",
                            Price = 5m,
                            WeightInGrams = 350
                        },
                        new
                        {
                            Id = "0cac471e-e654-4afc-bbde-bd2134be8ede",
                            CategoryId = 1,
                            Image = "https://www.oliveandmango.com/images/uploads/2021_06_21_classic_grilled_cheeseburger_1.jpg",
                            Name = "Cheese With Meatball",
                            Price = 5m,
                            WeightInGrams = 320
                        },
                        new
                        {
                            Id = "88f9cd46-13dc-4033-8a57-151d09f24c8f",
                            CategoryId = 2,
                            Image = "https://www.jocooks.com/wp-content/uploads/2012/03/margherita-pizza-11.jpg",
                            Name = "Margherita",
                            Price = 8.20m,
                            WeightInGrams = 400
                        },
                        new
                        {
                            Id = "6076b0f5-75d1-4e24-85be-1a3cf3654e61",
                            CategoryId = 2,
                            Image = "https://www.happyfoodstube.com/wp-content/uploads/2016/03/calzone-pizza-recipe.jpg",
                            Name = "Calzone",
                            Price = 10.50m,
                            WeightInGrams = 500
                        },
                        new
                        {
                            Id = "84cbe7b0-01cf-472d-9745-509d00ca9b72",
                            CategoryId = 2,
                            Image = "https://myfoodbook.com.au/sites/default/files/styles/schema_img/public/recipe_photo/pepperoni-pizza.jpg",
                            Name = "Pepperoni",
                            Price = 9.40m,
                            WeightInGrams = 400
                        },
                        new
                        {
                            Id = "98e94aef-bef9-4cdf-b9db-ad946ad7a9b9",
                            CategoryId = 3,
                            Image = "https://www.recipetineats.com/wp-content/uploads/2017/11/Chicken-Doner-Kebab-1-SQ.jpg",
                            Name = "Small Chicken Doner",
                            Price = 3m,
                            WeightInGrams = 200
                        },
                        new
                        {
                            Id = "60b297c4-61f1-4992-8952-d09759dff272",
                            CategoryId = 3,
                            Image = "https://www.recipetineats.com/wp-content/uploads/2017/11/Chicken-Doner-Kebab-1-SQ.jpg",
                            Name = "Middle Chicken Doner",
                            Price = 4m,
                            WeightInGrams = 300
                        },
                        new
                        {
                            Id = "87c6bea9-31f0-4d82-94f8-4cd522b6c90f",
                            CategoryId = 3,
                            Image = "https://www.recipetineats.com/wp-content/uploads/2017/11/Chicken-Doner-Kebab-1-SQ.jpg",
                            Name = "Big Chicken Doner",
                            Price = 5m,
                            WeightInGrams = 400
                        },
                        new
                        {
                            Id = "f969642a-bc37-4107-871d-c5ce4d10b163",
                            CategoryId = 3,
                            Image = "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/slow-cooker-lamb-kebab-1584109373.jpg",
                            Name = "Small Pork Doner",
                            Price = 3m,
                            WeightInGrams = 200
                        },
                        new
                        {
                            Id = "576ac9e8-633f-4693-9a18-d9f88f939560",
                            CategoryId = 3,
                            Image = "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/slow-cooker-lamb-kebab-1584109373.jpg",
                            Name = "Middle Pork Doner",
                            Price = 4m,
                            WeightInGrams = 300
                        },
                        new
                        {
                            Id = "b758ca67-6daf-46d6-83d1-4d637fd25543",
                            CategoryId = 3,
                            Image = "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/slow-cooker-lamb-kebab-1584109373.jpg",
                            Name = "Big Pork Doner",
                            Price = 5m,
                            WeightInGrams = 400
                        },
                        new
                        {
                            Id = "f4bfdd80-22cb-44c6-a416-b370dc471e21",
                            CategoryId = 4,
                            Image = "https://embed.widencdn.net/img/beef/xsoogkvab0/1120x840px/slow-cooked-beef-risotto.eps?keep=c&u=7fueml",
                            Name = "Rissoto With Meat",
                            Price = 4.50m,
                            WeightInGrams = 300
                        },
                        new
                        {
                            Id = "d7860f6f-6d66-495c-b84c-dae0a7c3c00c",
                            CategoryId = 4,
                            Image = "https://img.taste.com.au/xNrBHHXt/taste/2016/11/chicken-and-vegetable-risotto-76118-1.jpeg",
                            Name = "Rissoto With Vegetables",
                            Price = 3.50m,
                            WeightInGrams = 300
                        },
                        new
                        {
                            Id = "64920379-597e-4bad-bd45-e2d2b5b7ada0",
                            CategoryId = 5,
                            Image = "https://www.thespruceeats.com/thmb/jJqSQhrXRmVbPeihyHS-JNy5DCk=/3465x2599/smart/filters:no_upscale()/croque-monsieur-classic-french-grilled-cheese-996061-hero-01-cbf77c357af042fa89080019757916f0.jpg",
                            Name = "Ham And Cheese",
                            Price = 3m,
                            WeightInGrams = 200
                        });
                });

            modelBuilder.Entity("BestFood.Infrastructure.Data.Models.ProductIngredient", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("IngredientId")
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("ProductId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("ProductIngredient");

                    b.HasData(
                        new
                        {
                            ProductId = "272970b2-99e5-489e-862f-0a40115b888d",
                            IngredientId = "f6903024-2ae3-403e-b7f4-a5cf074e4af7"
                        },
                        new
                        {
                            ProductId = "272970b2-99e5-489e-862f-0a40115b888d",
                            IngredientId = "4e3b02ca-c436-4827-bc1d-6a283ba44a54"
                        },
                        new
                        {
                            ProductId = "272970b2-99e5-489e-862f-0a40115b888d",
                            IngredientId = "20f84ff4-662d-4f0a-bc66-e9170c215a2a"
                        },
                        new
                        {
                            ProductId = "272970b2-99e5-489e-862f-0a40115b888d",
                            IngredientId = "2a63b060-acc5-41ad-844d-31209d33fa10"
                        },
                        new
                        {
                            ProductId = "272970b2-99e5-489e-862f-0a40115b888d",
                            IngredientId = "0b11bbb6-0d3d-4233-8f94-c6e11f9682fb"
                        },
                        new
                        {
                            ProductId = "272970b2-99e5-489e-862f-0a40115b888d",
                            IngredientId = "813bde29-b392-4c16-9a3f-65734d667b08"
                        },
                        new
                        {
                            ProductId = "ce94928c-75eb-402d-a905-9ac43aa78067",
                            IngredientId = "f6903024-2ae3-403e-b7f4-a5cf074e4af7"
                        },
                        new
                        {
                            ProductId = "ce94928c-75eb-402d-a905-9ac43aa78067",
                            IngredientId = "f6dec5d8-15c5-4074-afa9-0b218f18a5f3"
                        },
                        new
                        {
                            ProductId = "ce94928c-75eb-402d-a905-9ac43aa78067",
                            IngredientId = "20f84ff4-662d-4f0a-bc66-e9170c215a2a"
                        },
                        new
                        {
                            ProductId = "ce94928c-75eb-402d-a905-9ac43aa78067",
                            IngredientId = "2a63b060-acc5-41ad-844d-31209d33fa10"
                        },
                        new
                        {
                            ProductId = "ce94928c-75eb-402d-a905-9ac43aa78067",
                            IngredientId = "0b11bbb6-0d3d-4233-8f94-c6e11f9682fb"
                        },
                        new
                        {
                            ProductId = "ce94928c-75eb-402d-a905-9ac43aa78067",
                            IngredientId = "813bde29-b392-4c16-9a3f-65734d667b08"
                        },
                        new
                        {
                            ProductId = "0cac471e-e654-4afc-bbde-bd2134be8ede",
                            IngredientId = "f6903024-2ae3-403e-b7f4-a5cf074e4af7"
                        },
                        new
                        {
                            ProductId = "0cac471e-e654-4afc-bbde-bd2134be8ede",
                            IngredientId = "53d5a668-8b04-45d3-be64-60e8ae439894"
                        },
                        new
                        {
                            ProductId = "0cac471e-e654-4afc-bbde-bd2134be8ede",
                            IngredientId = "20f84ff4-662d-4f0a-bc66-e9170c215a2a"
                        },
                        new
                        {
                            ProductId = "0cac471e-e654-4afc-bbde-bd2134be8ede",
                            IngredientId = "2a63b060-acc5-41ad-844d-31209d33fa10"
                        },
                        new
                        {
                            ProductId = "0cac471e-e654-4afc-bbde-bd2134be8ede",
                            IngredientId = "0b11bbb6-0d3d-4233-8f94-c6e11f9682fb"
                        },
                        new
                        {
                            ProductId = "0cac471e-e654-4afc-bbde-bd2134be8ede",
                            IngredientId = "813bde29-b392-4c16-9a3f-65734d667b08"
                        },
                        new
                        {
                            ProductId = "0cac471e-e654-4afc-bbde-bd2134be8ede",
                            IngredientId = "58fbb498-4393-41d2-a0e7-d0c364a36cc5"
                        },
                        new
                        {
                            ProductId = "88f9cd46-13dc-4033-8a57-151d09f24c8f",
                            IngredientId = "0ad836b1-0b01-4b4a-ba36-9ded54ebaa85"
                        },
                        new
                        {
                            ProductId = "88f9cd46-13dc-4033-8a57-151d09f24c8f",
                            IngredientId = "5e27ab2b-8ed1-4f3b-87bd-cc52394088b4"
                        },
                        new
                        {
                            ProductId = "88f9cd46-13dc-4033-8a57-151d09f24c8f",
                            IngredientId = "a3b2844c-a654-40cd-8045-e93d89826173"
                        },
                        new
                        {
                            ProductId = "6076b0f5-75d1-4e24-85be-1a3cf3654e61",
                            IngredientId = "0ad836b1-0b01-4b4a-ba36-9ded54ebaa85"
                        },
                        new
                        {
                            ProductId = "6076b0f5-75d1-4e24-85be-1a3cf3654e61",
                            IngredientId = "bb1979e9-4c7b-412c-9e84-4598bfa0524e"
                        },
                        new
                        {
                            ProductId = "6076b0f5-75d1-4e24-85be-1a3cf3654e61",
                            IngredientId = "c20d21eb-326f-4011-b8ba-058399d972c6"
                        },
                        new
                        {
                            ProductId = "6076b0f5-75d1-4e24-85be-1a3cf3654e61",
                            IngredientId = "e9bf191c-3475-4240-885c-19daba91ca80"
                        },
                        new
                        {
                            ProductId = "6076b0f5-75d1-4e24-85be-1a3cf3654e61",
                            IngredientId = "0b11bbb6-0d3d-4233-8f94-c6e11f9682fb"
                        },
                        new
                        {
                            ProductId = "6076b0f5-75d1-4e24-85be-1a3cf3654e61",
                            IngredientId = "392ff29a-68b8-4c7c-81d6-a5deb6d5a0c2"
                        },
                        new
                        {
                            ProductId = "6076b0f5-75d1-4e24-85be-1a3cf3654e61",
                            IngredientId = "5e27ab2b-8ed1-4f3b-87bd-cc52394088b4"
                        },
                        new
                        {
                            ProductId = "6076b0f5-75d1-4e24-85be-1a3cf3654e61",
                            IngredientId = "9ad3222f-77f7-4d4e-b9a3-66030e993e67"
                        },
                        new
                        {
                            ProductId = "84cbe7b0-01cf-472d-9745-509d00ca9b72",
                            IngredientId = "0ad836b1-0b01-4b4a-ba36-9ded54ebaa85"
                        },
                        new
                        {
                            ProductId = "84cbe7b0-01cf-472d-9745-509d00ca9b72",
                            IngredientId = "c20d21eb-326f-4011-b8ba-058399d972c6"
                        },
                        new
                        {
                            ProductId = "84cbe7b0-01cf-472d-9745-509d00ca9b72",
                            IngredientId = "5e27ab2b-8ed1-4f3b-87bd-cc52394088b4"
                        },
                        new
                        {
                            ProductId = "84cbe7b0-01cf-472d-9745-509d00ca9b72",
                            IngredientId = "e9bf191c-3475-4240-885c-19daba91ca80"
                        },
                        new
                        {
                            ProductId = "98e94aef-bef9-4cdf-b9db-ad946ad7a9b9",
                            IngredientId = "d9979ac9-3401-4257-aded-cc37edd3becb"
                        },
                        new
                        {
                            ProductId = "98e94aef-bef9-4cdf-b9db-ad946ad7a9b9",
                            IngredientId = "33458ae4-b21f-4c39-8dff-44e87844a6a2"
                        },
                        new
                        {
                            ProductId = "98e94aef-bef9-4cdf-b9db-ad946ad7a9b9",
                            IngredientId = "e7791135-4cd6-4c94-afe9-1867dc19c338"
                        },
                        new
                        {
                            ProductId = "98e94aef-bef9-4cdf-b9db-ad946ad7a9b9",
                            IngredientId = "20f84ff4-662d-4f0a-bc66-e9170c215a2a"
                        },
                        new
                        {
                            ProductId = "98e94aef-bef9-4cdf-b9db-ad946ad7a9b9",
                            IngredientId = "2a63b060-acc5-41ad-844d-31209d33fa10"
                        },
                        new
                        {
                            ProductId = "98e94aef-bef9-4cdf-b9db-ad946ad7a9b9",
                            IngredientId = "0b11bbb6-0d3d-4233-8f94-c6e11f9682fb"
                        },
                        new
                        {
                            ProductId = "98e94aef-bef9-4cdf-b9db-ad946ad7a9b9",
                            IngredientId = "b48f7dc6-4077-4bfb-8ed4-8f4e8d616908"
                        },
                        new
                        {
                            ProductId = "60b297c4-61f1-4992-8952-d09759dff272",
                            IngredientId = "d9979ac9-3401-4257-aded-cc37edd3becb"
                        },
                        new
                        {
                            ProductId = "60b297c4-61f1-4992-8952-d09759dff272",
                            IngredientId = "33458ae4-b21f-4c39-8dff-44e87844a6a2"
                        },
                        new
                        {
                            ProductId = "60b297c4-61f1-4992-8952-d09759dff272",
                            IngredientId = "e7791135-4cd6-4c94-afe9-1867dc19c338"
                        },
                        new
                        {
                            ProductId = "60b297c4-61f1-4992-8952-d09759dff272",
                            IngredientId = "20f84ff4-662d-4f0a-bc66-e9170c215a2a"
                        },
                        new
                        {
                            ProductId = "60b297c4-61f1-4992-8952-d09759dff272",
                            IngredientId = "2a63b060-acc5-41ad-844d-31209d33fa10"
                        },
                        new
                        {
                            ProductId = "60b297c4-61f1-4992-8952-d09759dff272",
                            IngredientId = "0b11bbb6-0d3d-4233-8f94-c6e11f9682fb"
                        },
                        new
                        {
                            ProductId = "60b297c4-61f1-4992-8952-d09759dff272",
                            IngredientId = "b48f7dc6-4077-4bfb-8ed4-8f4e8d616908"
                        },
                        new
                        {
                            ProductId = "87c6bea9-31f0-4d82-94f8-4cd522b6c90f",
                            IngredientId = "d9979ac9-3401-4257-aded-cc37edd3becb"
                        },
                        new
                        {
                            ProductId = "87c6bea9-31f0-4d82-94f8-4cd522b6c90f",
                            IngredientId = "33458ae4-b21f-4c39-8dff-44e87844a6a2"
                        },
                        new
                        {
                            ProductId = "87c6bea9-31f0-4d82-94f8-4cd522b6c90f",
                            IngredientId = "e7791135-4cd6-4c94-afe9-1867dc19c338"
                        },
                        new
                        {
                            ProductId = "87c6bea9-31f0-4d82-94f8-4cd522b6c90f",
                            IngredientId = "20f84ff4-662d-4f0a-bc66-e9170c215a2a"
                        },
                        new
                        {
                            ProductId = "87c6bea9-31f0-4d82-94f8-4cd522b6c90f",
                            IngredientId = "2a63b060-acc5-41ad-844d-31209d33fa10"
                        },
                        new
                        {
                            ProductId = "87c6bea9-31f0-4d82-94f8-4cd522b6c90f",
                            IngredientId = "0b11bbb6-0d3d-4233-8f94-c6e11f9682fb"
                        },
                        new
                        {
                            ProductId = "87c6bea9-31f0-4d82-94f8-4cd522b6c90f",
                            IngredientId = "b48f7dc6-4077-4bfb-8ed4-8f4e8d616908"
                        },
                        new
                        {
                            ProductId = "f969642a-bc37-4107-871d-c5ce4d10b163",
                            IngredientId = "d9979ac9-3401-4257-aded-cc37edd3becb"
                        },
                        new
                        {
                            ProductId = "f969642a-bc37-4107-871d-c5ce4d10b163",
                            IngredientId = "33458ae4-b21f-4c39-8dff-44e87844a6a2"
                        },
                        new
                        {
                            ProductId = "f969642a-bc37-4107-871d-c5ce4d10b163",
                            IngredientId = "c751debf-36b1-4801-af56-8c9096f34309"
                        },
                        new
                        {
                            ProductId = "f969642a-bc37-4107-871d-c5ce4d10b163",
                            IngredientId = "20f84ff4-662d-4f0a-bc66-e9170c215a2a"
                        },
                        new
                        {
                            ProductId = "f969642a-bc37-4107-871d-c5ce4d10b163",
                            IngredientId = "2a63b060-acc5-41ad-844d-31209d33fa10"
                        },
                        new
                        {
                            ProductId = "f969642a-bc37-4107-871d-c5ce4d10b163",
                            IngredientId = "0b11bbb6-0d3d-4233-8f94-c6e11f9682fb"
                        },
                        new
                        {
                            ProductId = "f969642a-bc37-4107-871d-c5ce4d10b163",
                            IngredientId = "b48f7dc6-4077-4bfb-8ed4-8f4e8d616908"
                        },
                        new
                        {
                            ProductId = "576ac9e8-633f-4693-9a18-d9f88f939560",
                            IngredientId = "d9979ac9-3401-4257-aded-cc37edd3becb"
                        },
                        new
                        {
                            ProductId = "576ac9e8-633f-4693-9a18-d9f88f939560",
                            IngredientId = "33458ae4-b21f-4c39-8dff-44e87844a6a2"
                        },
                        new
                        {
                            ProductId = "576ac9e8-633f-4693-9a18-d9f88f939560",
                            IngredientId = "c751debf-36b1-4801-af56-8c9096f34309"
                        },
                        new
                        {
                            ProductId = "576ac9e8-633f-4693-9a18-d9f88f939560",
                            IngredientId = "20f84ff4-662d-4f0a-bc66-e9170c215a2a"
                        },
                        new
                        {
                            ProductId = "576ac9e8-633f-4693-9a18-d9f88f939560",
                            IngredientId = "2a63b060-acc5-41ad-844d-31209d33fa10"
                        },
                        new
                        {
                            ProductId = "576ac9e8-633f-4693-9a18-d9f88f939560",
                            IngredientId = "0b11bbb6-0d3d-4233-8f94-c6e11f9682fb"
                        },
                        new
                        {
                            ProductId = "576ac9e8-633f-4693-9a18-d9f88f939560",
                            IngredientId = "b48f7dc6-4077-4bfb-8ed4-8f4e8d616908"
                        },
                        new
                        {
                            ProductId = "b758ca67-6daf-46d6-83d1-4d637fd25543",
                            IngredientId = "d9979ac9-3401-4257-aded-cc37edd3becb"
                        },
                        new
                        {
                            ProductId = "b758ca67-6daf-46d6-83d1-4d637fd25543",
                            IngredientId = "33458ae4-b21f-4c39-8dff-44e87844a6a2"
                        },
                        new
                        {
                            ProductId = "b758ca67-6daf-46d6-83d1-4d637fd25543",
                            IngredientId = "c751debf-36b1-4801-af56-8c9096f34309"
                        },
                        new
                        {
                            ProductId = "b758ca67-6daf-46d6-83d1-4d637fd25543",
                            IngredientId = "20f84ff4-662d-4f0a-bc66-e9170c215a2a"
                        },
                        new
                        {
                            ProductId = "b758ca67-6daf-46d6-83d1-4d637fd25543",
                            IngredientId = "2a63b060-acc5-41ad-844d-31209d33fa10"
                        },
                        new
                        {
                            ProductId = "b758ca67-6daf-46d6-83d1-4d637fd25543",
                            IngredientId = "0b11bbb6-0d3d-4233-8f94-c6e11f9682fb"
                        },
                        new
                        {
                            ProductId = "b758ca67-6daf-46d6-83d1-4d637fd25543",
                            IngredientId = "b48f7dc6-4077-4bfb-8ed4-8f4e8d616908"
                        },
                        new
                        {
                            ProductId = "f4bfdd80-22cb-44c6-a416-b370dc471e21",
                            IngredientId = "e7791135-4cd6-4c94-afe9-1867dc19c338"
                        },
                        new
                        {
                            ProductId = "d7860f6f-6d66-495c-b84c-dae0a7c3c00c",
                            IngredientId = "20f84ff4-662d-4f0a-bc66-e9170c215a2a"
                        },
                        new
                        {
                            ProductId = "d7860f6f-6d66-495c-b84c-dae0a7c3c00c",
                            IngredientId = "2a63b060-acc5-41ad-844d-31209d33fa10"
                        },
                        new
                        {
                            ProductId = "d7860f6f-6d66-495c-b84c-dae0a7c3c00c",
                            IngredientId = "b8ae6779-3469-4669-89f2-932b49d46fdc"
                        },
                        new
                        {
                            ProductId = "d7860f6f-6d66-495c-b84c-dae0a7c3c00c",
                            IngredientId = "0b11bbb6-0d3d-4233-8f94-c6e11f9682fb"
                        },
                        new
                        {
                            ProductId = "64920379-597e-4bad-bd45-e2d2b5b7ada0",
                            IngredientId = "2f723a91-bc11-4104-bb01-6d4ebbc60fc5"
                        },
                        new
                        {
                            ProductId = "64920379-597e-4bad-bd45-e2d2b5b7ada0",
                            IngredientId = "20f84ff4-662d-4f0a-bc66-e9170c215a2a"
                        },
                        new
                        {
                            ProductId = "64920379-597e-4bad-bd45-e2d2b5b7ada0",
                            IngredientId = "2a63b060-acc5-41ad-844d-31209d33fa10"
                        },
                        new
                        {
                            ProductId = "64920379-597e-4bad-bd45-e2d2b5b7ada0",
                            IngredientId = "58fbb498-4393-41d2-a0e7-d0c364a36cc5"
                        });
                });

            modelBuilder.Entity("BestFood.Infrastructure.Data.Models.Review", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8881f953-e7cc-4d0d-8937-9a74413e60c5",
                            ConcurrencyStamp = "df8dc182-f408-4dcd-82d7-0c6ae14ccfe3",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "df578c9e-41dc-48e6-b352-5f4f33577c63",
                            ConcurrencyStamp = "5938b091-e31f-47d4-a92d-781a3306074c",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "bcc9e639-b998-466b-8d67-5e7dda1dfe5a",
                            RoleId = "8881f953-e7cc-4d0d-8937-9a74413e60c5"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BestFood.Infrastructure.Data.Models.CartItem", b =>
                {
                    b.HasOne("BestFood.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("ShoppingCartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BestFood.Infrastructure.Data.Models.CategoryIngredient", b =>
                {
                    b.HasOne("BestFood.Infrastructure.Data.Models.Category", "Category")
                        .WithMany("CategoriesIngredients")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BestFood.Infrastructure.Data.Models.Ingredient", "Ingredient")
                        .WithMany("CategoryIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("BestFood.Infrastructure.Data.Models.Order", b =>
                {
                    b.HasOne("BestFood.Infrastructure.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Orders")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("BestFood.Infrastructure.Data.Models.Product", b =>
                {
                    b.HasOne("BestFood.Infrastructure.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BestFood.Infrastructure.Data.Models.ProductIngredient", b =>
                {
                    b.HasOne("BestFood.Infrastructure.Data.Models.Ingredient", "Ingredient")
                        .WithMany("ProductIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BestFood.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("ProductsIngredients")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BestFood.Infrastructure.Data.Models.Review", b =>
                {
                    b.HasOne("BestFood.Infrastructure.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Reviews")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BestFood.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BestFood.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BestFood.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BestFood.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BestFood.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BestFood.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BestFood.Infrastructure.Data.Models.Category", b =>
                {
                    b.Navigation("CategoriesIngredients");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("BestFood.Infrastructure.Data.Models.Ingredient", b =>
                {
                    b.Navigation("CategoryIngredients");

                    b.Navigation("ProductIngredients");
                });

            modelBuilder.Entity("BestFood.Infrastructure.Data.Models.Product", b =>
                {
                    b.Navigation("ProductsIngredients");

                    b.Navigation("Reviews");

                    b.Navigation("ShoppingCartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
